### ISSUE TITLE
Only partly loading .mat file to avoid buffer overload.

### ISSUE THREAD

**Issue by kldjonge** [jraedler/DyMat#4]
Hi! I generated a large .mat file from a complex simulation.  DyMat crashes because the file it wants to load in is to big.  Is it possible to only load in the data I want right from the start? 

I am not a python expert so I could be wrong here but I noticed in the error log that DyMat is based on scipy.io.loadmat. 
This function as such has the optional argument 'variable_names' to choose to not load certain data from the total file. 
https://docs.scipy.org/doc/scipy/reference/generated/scipy.io.loadmat.html

Could it be possible to propagate this optional argument so that DyMat can also handle bigger files?

**Comment by jraedler** [comment]
In the last years I didn't use Modelica simulations anymore, so I don't have time or tools for further development or testing of this project. Sorry! If you can provide a working patch I will accept it.
